name: Build app
run-name: Build android app
on: [ push ]
jobs:
  build-android-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
      - run: flutter pub get
      - run: flutter pub run flutter_native_splash:create
      - run: flutter packages pub run build_runner build
      - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle